<a href="https://colab.research.google.com/github/Shenbagapriya24/Assignments/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version

In [3]:
np.version.version

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10,np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
#Problem 4: Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'.
import numpy as np
a = np.array([1,2,3,4,5])
print(a.dtype)

a = np.array([1,2,3,4,5],np.float64)
print(a.dtype)


int64
float64


6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 4. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [3]:
arrA = np.array([[1,2,3],[4,5,6]])
print(arrA[0:1])

[[1 2 3]]


#### 5. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a = np.arange(10,50)
b = a[-1:-49:-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
x = np.arange(0,9)
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [4]:
a = np.array([1,2,0,0,4,0])
b = np.nonzero(a)
print(b)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a = np.random.randint(10, size=(3,3,3))
print(a)

[[[3 1 4]
  [7 4 1]
  [7 9 4]]

 [[0 9 6]
  [0 5 9]
  [3 6 0]]

 [[7 8 3]
  [8 1 5]
  [6 6 9]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a = np.random.randint(100, size=(10,10))
print("Minimum value is" , np.min(a))
print("Maximum value is" , np.max(a))

Minimum value is 2
Maximum value is 99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np
a = np.random.randint(30, size=(30))
b = np.mean(a)
print(b)

14.533333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan         #nan
np.nan == np.nan  #false
np.inf > np.nan   #false
np.nan - np.nan   #nan
np.nan in set([np.nan])   #true
0.3 == 3 * 0.1    #false coz of precision

#### 18. Create a 4x4 matrix with values 0,1,2,3 just below the diagonal (★☆☆)

In [3]:
import numpy as np
x = np.diag(np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


#### 19. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
---



In [4]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 22. Normalize a 5x5 random matrix (★☆☆) Say X is 5*5 numpy array  Normalize i.e X - mean(X) / Standard Deviation of X [link text](https://)

In [4]:
import numpy as np
x= np.random.random((5,5))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

[[0.0524806  0.73796944 0.15677379 0.25383198 0.81802146]
 [0.1915337  0.39082907 0.26175227 0.94927749 0.60125331]
 [0.47434529 0.66560682 0.61529985 0.67558068 0.72490892]
 [0.07062482 0.86412735 0.62998979 0.03885611 0.46416667]
 [0.66674007 0.72851243 0.3758776  0.84980629 0.03575846]]
After normalization:
[[0.01830519 0.76868785 0.1324716  0.23871809 0.85631823]
 [0.17052216 0.38868442 0.24738818 1.         0.61902908]
 [0.48010694 0.68947482 0.63440539 0.70039288 0.75439092]
 [0.03816709 0.90678887 0.65048599 0.0033909  0.46896474]
 [0.69071534 0.75833557 0.37231753 0.89111207 0.        ]]


#### 23. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [8]:
arrA = np.array([[1,2,3],[4,5,6]])
print(arrA[0:1])

[[1 2 3]]


#### 24. Do a dot product of 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
a = np.random.randint(5,size=(5,3))
b = np.random.randint(5,size=(3,2))
x = np.dot(a,b)
print(x)

[[10  0]
 [13  2]
 [ 9  4]
 [ 5  2]
 [18  8]]


#### 25. Consider two random array A and B, check if they are equal (★★☆)

In [13]:
a = np.random.rand(5)
b = np.random.rand(5)
print(a==b)
print(np.allclose(a,b))

[False False False False False]
False


#### 26. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.60717061 0.38503747 0.51138771 0.         0.38608688 0.85272738
 0.22324245 0.10190758 0.71323106 0.84788563]


#### 27. Subtract the mean of each row of a matrix (★★☆):

In [5]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.2621171  0.3060149  0.94265633 0.02131426 0.04356761 0.96030021
  0.707378   0.38867762 0.44650665 0.85158844]
 [0.58584591 0.35251098 0.71514519 0.39242577 0.89105343 0.35792843
  0.86221007 0.40988299 0.59042994 0.84684587]
 [0.26601275 0.36441168 0.86109468 0.48763742 0.93108244 0.0036448
  0.7617067  0.43486083 0.2748615  0.14968437]
 [0.78156514 0.73123479 0.22150399 0.40750571 0.73819059 0.57352517
  0.01148758 0.49554051 0.70127712 0.44626838]
 [0.20340961 0.18920732 0.67196792 0.52924187 0.42262269 0.69068052
  0.30000203 0.93044359 0.50989264 0.30812016]]

Subtract the mean of each row of the said matrix:

[[-0.23089501 -0.18699722  0.44964422 -0.47169785 -0.4494445   0.46728809
   0.21436589 -0.10433449 -0.04650546  0.35857633]
 [-0.01458194 -0.24791688  0.11471733 -0.20800209  0.29062557 -0.24249943
   0.26178221 -0.19054487 -0.00999792  0.24641801]
 [-0.18748697 -0.08908804  0.40759496  0.0341377   0.47758273 -0.44985491
   0.30820699 -0.01863888 -0.17